config {
    type: "table",
    schema: "dataform_staging",
    name: "click_events_latest",
    description: "Eventi filtrati con prefisso click_ dall'ultima partizione disponibile"
}

SELECT
  *
FROM
  ${ref("analytics_517838177", "events_*")}
WHERE
  event_name LIKE 'click_%'
  AND _TABLE_SUFFIX = (
    SELECT
      MAX(_TABLE_SUFFIX)
    FROM
      ${ref("analytics_517838177", "events_*")}
  )